management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有端口
    enabled-by-default: true # 启用所有端口
cxf:
  jaxrs:
    classes-scan: true
    classes-scan-packages: com.ale
    server:
#      path: / # customize a JAX-RS server endpoint address (default is "/").
#      address: http://localhost:9090/
    client:
      address: http://localhost:11111/
      classes-scan-packages: com.ale.rest.client
#  path: /services # customize a CXFServlet URL pattern.

spring:
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 1000
    lettuce:
      pool:
        max-idle: 200
        min-idle: 0
        max-active: 200
        max-wait: 1000
