DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id    BIGINT(20)  NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    name  VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    age   INT(11)     NULL DEFAULT NULL COMMENT '年龄',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS dept;
CREATE TABLE dept
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    dept_name VARCHAR(30) NULL DEFAULT NULL COMMENT '部门名称',
    PRIMARY KEY (id)
);