DROP TABLE IF EXISTS student;

CREATE TABLE student
(
    id   BIGINT(20)  NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    sex  INT(11)     NULL DEFAULT NULL COMMENT '性别',
    PRIMARY KEY (id)
);
