spring:

  redis:
    redisson:
      config: classpath:redisson.yml
    host: 106.54.243.76
    port: 6479
    timeout: 100
    password: abc123.
    lettuce:
      pool:
        max-active: 2
        max-idle: 1
logging:
  pattern:
    level: debug